### ISSUE TITLE
Subscript out of bounds error

### ISSUE THREAD

**Issue by dominicshore** [DataWookie/flipsideR#2]
When I try to loop through a list of all ASX companies which currently have options trading and pass their names to the getOptionChainAsx function, I get the error 

> Error in (html %>% html_nodes("table.options") %>% html_table(header = TRUE))[[2]] : subscript out of bounds

This is the chunk of code that returns the error:

```
require(data.table)
require(flipsideR)

master.list<-read.csv("http://www.asx.com.au/data/ASXCLDerivativesMasterList.csv")
coys<-as.data.table(as.character(unique(master.list$Underlying)))
for (i in 1:dim(coys)[1]) {rbind(opts, getOptionChainAsx(as.character(coys[i])))}
```

**Comment by datawookie** [comment]
Hi Dom,

Okay, the underlying problem was that most symbols have both a Shares and an Options table (see, for example, the data for [AGL](http://www.asx.com.au/asx/markets/optionPrices.do?by=underlyingCode&underlyingCode=AGL&expiryDate=&optionType=B)). Some of them only have an Options table (for example, [AM8](http://www.asx.com.au/asx/markets/optionPrices.do?by=underlyingCode&underlyingCode=AM8&expiryDate=&optionType=B)). I hadn't catered for the latter case. The code has been updated to work with both scenarios now.

I'd also suggest a small change to the way that you retrieve the data. This worked well for me:

```
library(dplyr)
require(flipsideR)

master.list <- read.csv("ASXCLDerivativesMasterList.csv")

opts <- lapply(as.character(unique(master.list$Underlying)), function(i) {
  print(i)
  getOptionChain(i, exchange = "ASX")
})
opts <- bind_rows(opts)
```

Let me know if this resolves your issue.

Best regards, Andrew.

**Comment by dominicshore** [comment]
Hi Andrew,

Thank you so much for that, I really appreciate it. I've being trying to
figure out how to make it work for about 10 days - as I said, I'm just
starting out!


Regards

Dom

**Comment by datawookie** [comment]
Hi Dom,

Please check my response on GitHub. There's a revised version of the 
package which should sort out this issue. I have also provided some 
alternative code to do your download (see my comment on the Issues page).

Let me know how this works out for you.

Best regards,
Andrew.

On 24/02/2016 09:40, dominicshore wrote:

> When I try to loop through a list of all ASX companies which currently 
> have options trading and pass their names to the getOptionChainAsx 
> function, I get the error
> 
> ```
> Error in (html %>% html_nodes("table.options") %>%
> html_table(header = TRUE))[[2]] : subscript out of bounds
> ```
> 
> This is the chunk of code that returns the error:
> 
> |require(data.table)|
> |require(flipsideR)|
> 
> `master.list<-read.csv("http://www.asx.com.au/data/ASXCLDerivativesMasterList.csv")'
> 'coys<-as.data.table(as.character(unique(master.list$Underlying)))'
> 'for (i in 1:dim(coys)[1]) {'
> 
> 'rbind(opts, getOptionChainAsx(as.character(coys[i])))'
> 
> '}'
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/DataWookie/flipsideR/issues/2.

## 

Andrew B. Collier, PhD                           http://www.exegetic.biz
Exegetic Analytics                                        +27 83 3813655
http://za.linkedin.com/in/collierab/                    skype: abcollier
